import os
import uuid
from datetime import datetime
from typing import Optional
from jinja2 import Template
from app.config import settings
from app.utils.logger import get_logger

logger = get_logger(__name__)

REPORT_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>VulNexus Security Audit Report</title>
<style>
body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #222; }
h1 { color: #1a237e; border-bottom: 3px solid #1a237e; padding-bottom: 10px; }
h2 { color: #283593; margin-top: 30px; }
h3 { color: #3949ab; }
.meta { color: #555; font-size: 0.9em; margin-bottom: 20px; }
.severity-critical { color: #b71c1c; font-weight: bold; }
.severity-high { color: #e65100; font-weight: bold; }
.severity-medium { color: #f9a825; font-weight: bold; }
.severity-low { color: #2e7d32; font-weight: bold; }
table { width: 100%; border-collapse: collapse; margin: 15px 0; }
th, td { border: 1px solid #ccc; padding: 10px; text-align: left; }
th { background: #e8eaf6; }
.score-badge { display: inline-block; padding: 8px 16px; border-radius: 20px;
    color: white; font-size: 1.2em; font-weight: bold; }
.score-critical { background: #b71c1c; }
.score-high { background: #e65100; }
.score-medium { background: #f9a825; color: #222; }
.score-low { background: #2e7d32; }
.summary-box { background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 15px 0; }
.remediation { background: #e8f5e9; padding: 15px; border-left: 4px solid #2e7d32; margin: 10px 0; }
footer { margin-top: 40px; border-top: 1px solid #ccc; padding-top: 10px;
    font-size: 0.8em; color: #888; }
</style>
</head>
<body>

<h1>VulNexus Cryptography Security Audit Report</h1>
<div class="meta">
    <p><strong>Scan ID:</strong> {{ scan_id }}</p>
    <p><strong>Target:</strong> {{ target }}</p>
    <p><strong>Scan Type:</strong> {{ scan_type }}</p>
    <p><strong>Generated:</strong> {{ generated_at }}</p>
    <p><strong>Scan Started:</strong> {{ started_at or 'N/A' }}</p>
    <p><strong>Scan Finished:</strong> {{ finished_at or 'N/A' }}</p>
</div>

<h2>Executive Summary</h2>
<div class="summary-box">
    <p>This automated security audit scanned <strong>{{ target }}</strong> for cryptographic
    vulnerabilities. The scan identified <strong>{{ vuln_count }}</strong> potential issues.</p>

    <p>Overall AI Risk Score:
    <span class="score-badge score-{{ score_class }}">{{ overall_score }} / 100</span>
    </p>

    <p>Severity Breakdown:</p>
    <ul>
        <li class="severity-critical">Critical: {{ severity_counts.get('Critical', 0) }}</li>
        <li class="severity-high">High: {{ severity_counts.get('High', 0) }}</li>
        <li class="severity-medium">Medium: {{ severity_counts.get('Medium', 0) }}</li>
        <li class="severity-low">Low: {{ severity_counts.get('Low', 0) }}</li>
    </ul>
</div>

<h2>Vulnerabilities</h2>
{% if vulnerabilities %}
<table>
<tr>
    <th>#</th><th>Rule ID</th><th>Severity</th><th>Description</th>
    <th>AI Score</th><th>CVE</th><th>File</th><th>Line</th>
</tr>
{% for v in vulnerabilities %}
<tr>
    <td>{{ loop.index }}</td>
    <td>{{ v.rule_id or 'N/A' }}</td>
    <td class="severity-{{ v.severity|lower }}">{{ v.severity }}</td>
    <td>{{ v.description }}</td>
    <td>{{ v.ml_score if v.ml_score is not none else 'N/A' }}</td>
    <td>{{ v.cve_id or 'N/A' }}</td>
    <td>{{ v.file_path or 'N/A' }}</td>
    <td>{{ v.line_number or 'N/A' }}</td>
</tr>
{% endfor %}
</table>
{% else %}
<p>No vulnerabilities detected.</p>
{% endif %}

{% if cve_details %}
<h2>CVE References</h2>
<table>
<tr><th>CVE ID</th><th>CVSS</th><th>Summary</th><th>Published</th></tr>
{% for c in cve_details %}
<tr>
    <td>{{ c.cve_id }}</td>
    <td>{{ c.cvss_score or 'N/A' }}</td>
    <td>{{ c.summary or 'N/A' }}</td>
    <td>{{ c.published_date or 'N/A' }}</td>
</tr>
{% endfor %}
</table>
{% endif %}

<h2>Remediation Guidance</h2>
{% for v in vulnerabilities %}
{% if v.remediation %}
<div class="remediation">
    <h3>{{ v.rule_id or 'Issue' }} — {{ v.severity }}</h3>
    <p>{{ v.remediation }}</p>
</div>
{% endif %}
{% endfor %}

<div class="remediation">
<h3>General Recommendations</h3>
<ul>
    <li>Replace MD5/SHA-1 with SHA-256 or SHA-3</li>
    <li>Replace DES/3DES/RC2 with AES-256-GCM</li>
    <li>Use RSA ≥ 2048 bits or ECDSA ≥ P-256</li>
    <li>Enable TLS 1.2+ and disable older versions</li>
    <li>Enable HSTS with a minimum max-age of 31536000</li>
    <li>Use certificates from trusted CAs</li>
    <li>Use cryptographically secure random number generators</li>
    <li>Never hardcode keys or secrets — use a secrets manager</li>
</ul>
</div>

<footer>
    <p>Generated by VulNexus — AI-Based Cryptography Vulnerability Scanner</p>
    <p>Report ID: {{ scan_id }} | {{ generated_at }}</p>
</footer>

</body>
</html>
"""

REMEDIATION_MAP = {
    "WEAK_HASH_MD5": "Replace MD5 with SHA-256 or SHA-3. MD5 is vulnerable to collision attacks (RFC 6151).",
    "WEAK_HASH_SHA1": "Replace SHA-1 with SHA-256 or SHA-3. SHA-1 is vulnerable to collision attacks (NIST SP 800-131A).",
    "WEAK_CIPHER_DES": "Replace DES with AES-256-GCM. DES has a 56-bit key which is trivially brute-forceable.",
    "WEAK_CIPHER_RC2": "Replace RC2 with AES-256-GCM. RC2 is considered cryptographically weak.",
    "WEAK_CIPHER_AES-ECB": "Replace ECB mode with GCM or CBC with proper IV. ECB leaks patterns in plaintext.",
    "SMALL_RSA_KEY": "Use RSA key size of 2048 bits minimum (NIST recommendation). Consider 4096 for long-term security.",
    "SMALL_AES_KEY": "Use AES-128 minimum; AES-256 recommended for sensitive data.",
    "HARDCODED_KEY": "Move keys to environment variables or a secrets manager (e.g., AWS Secrets Manager, HashiCorp Vault).",
    "INSECURE_RANDOM": "Use os.urandom(), secrets module (Python), or java.security.SecureRandom (Java).",
    "WEAK_TLS_VERSION": "Disable TLS 1.0/1.1 and enable TLS 1.2+ (PCI DSS 3.2 requirement).",
    "SELF_SIGNED_CERT": "Use certificates from a trusted CA. Use Let's Encrypt for free certificates.",
    "NO_HSTS": "Add Strict-Transport-Security header with max-age=31536000; includeSubDomains.",
    "NO_FORWARD_SECRECY": "Configure server to prefer ECDHE cipher suites for forward secrecy.",
    "EXPIRED_CERT": "Renew the expired certificate immediately. Set up automated renewal.",
    "USES_MD5": "Replace MD5 with SHA-256 or SHA-3.",
    "USES_SHA1": "Replace SHA-1 with SHA-256 or SHA-3.",
    "USES_DES": "Replace DES with AES-256-GCM.",
    "USES_RC2": "Replace RC2 with AES-256-GCM.",
    "USES_ECB": "Replace ECB mode with GCM or CBC.",
    "RSA_SMALL": "Use RSA ≥ 2048 bits.",
    "AES_SMALL": "Use AES ≥ 128 bits.",
    "NO_PFS": "Enable ECDHE cipher suites for forward secrecy.",
    "WEAK_TLS": "Upgrade to TLS 1.2 or higher.",
    "SELF_SIGNED": "Use a certificate from a trusted CA.",
}


def get_remediation(rule_id: str) -> str:
    return REMEDIATION_MAP.get(rule_id, "Review and update the cryptographic configuration per current best practices.")


def generate_html_report(
    scan_id: str,
    target: str,
    scan_type: str,
    overall_score: float,
    vulnerabilities: list[dict],
    cve_details: list[dict],
    started_at: Optional[str] = None,
    finished_at: Optional[str] = None,
) -> str:
    for v in vulnerabilities:
        if not v.get("remediation") and v.get("rule_id"):
            v["remediation"] = get_remediation(v["rule_id"])

    severity_counts = {}
    for v in vulnerabilities:
        sev = v.get("severity", "Unknown")
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    if overall_score >= 75:
        score_class = "critical"
    elif overall_score >= 50:
        score_class = "high"
    elif overall_score >= 25:
        score_class = "medium"
    else:
        score_class = "low"

    template = Template(REPORT_TEMPLATE)
    return template.render(
        scan_id=scan_id,
        target=target,
        scan_type=scan_type,
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
        started_at=started_at,
        finished_at=finished_at,
        overall_score=round(overall_score, 1),
        score_class=score_class,
        vuln_count=len(vulnerabilities),
        severity_counts=severity_counts,
        vulnerabilities=vulnerabilities,
        cve_details=cve_details,
    )


def generate_pdf_report(html_content: str, output_path: str) -> str:
    try:
        from weasyprint import HTML
        HTML(string=html_content).write_pdf(output_path)
        return output_path
    except ImportError:
        html_path = output_path.replace(".pdf", ".html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html_content)
        logger.warning("WeasyPrint not available, saved HTML report instead")
        return html_path


def build_report(
    scan_id: uuid.UUID,
    target: str,
    scan_type: str,
    overall_score: float,
    vulnerabilities: list[dict],
    cve_details: list[dict],
    started_at=None,
    finished_at=None,
) -> str:
    reports_dir = os.path.join(settings.UPLOAD_DIR, "reports")
    os.makedirs(reports_dir, exist_ok=True)

    html = generate_html_report(
        scan_id=str(scan_id),
        target=target,
        scan_type=scan_type,
        overall_score=overall_score,
        vulnerabilities=vulnerabilities,
        cve_details=cve_details,
        started_at=str(started_at) if started_at else None,
        finished_at=str(finished_at) if finished_at else None,
    )

    pdf_path = os.path.join(reports_dir, f"{scan_id}.pdf")
    return generate_pdf_report(html, pdf_path)
