from __future__ import annotations

import base64
from dataclasses import dataclass
from typing import Protocol

from app.config import settings
from app.utils.logger import get_logger

logger = get_logger(__name__)


class ReportRenderer(Protocol):
    async def render_pdf(self, html_content: str, output_path: str, *, metadata: dict | None = None) -> str:
        """Render HTML content to a PDF file and return the generated path."""


@dataclass(slots=True)
class RenderOptions:
    header_text: str | None = None
    footer_text: str | None = None
    display_header_footer: bool = True
    print_background: bool = True
    prefer_css_page_size: bool = True
    margin_top: str = "18mm"
    margin_right: str = "14mm"
    margin_bottom: str = "18mm"
    margin_left: str = "14mm"


class PlaywrightChromiumRenderer:
    def __init__(self, browser_path: str | None = None):
        self.browser_path = browser_path or settings.PLAYWRIGHT_BROWSER_PATH

    async def render_pdf(self, html_content: str, output_path: str, *, metadata: dict | None = None) -> str:
        try:
            from playwright.async_api import async_playwright
        except ImportError as exc:  # pragma: no cover - dependency bootstrap failure
            raise RuntimeError(
                "Playwright is required for PDF rendering. Install playwright and run 'playwright install chromium'."
            ) from exc

        options = RenderOptions(
            header_text=(metadata or {}).get("header_text") or settings.REPORT_PDF_HEADER,
            footer_text=(metadata or {}).get("footer_text") or settings.REPORT_PDF_FOOTER,
        )

        browser_launch_args = ["--disable-dev-shm-usage", "--disable-gpu", "--no-sandbox"]
        async with async_playwright() as p:
            browser = await p.chromium.launch(
                headless=True,
                executable_path=self.browser_path,
                args=browser_launch_args,
            )
            try:
                page = await browser.new_page(viewport={"width": 1440, "height": 1024}, device_scale_factor=1)
                await page.set_content(html_content, wait_until="networkidle")
                await page.emulate_media(media="print")

                header_template = self._build_header_template(options.header_text)
                footer_template = self._build_footer_template(options.footer_text)

                await page.pdf(
                    path=output_path,
                    format="A4",
                    print_background=options.print_background,
                    prefer_css_page_size=options.prefer_css_page_size,
                    display_header_footer=options.display_header_footer,
                    header_template=header_template,
                    footer_template=footer_template,
                    margin={
                        "top": options.margin_top,
                        "right": options.margin_right,
                        "bottom": options.margin_bottom,
                        "left": options.margin_left,
                    },
                )
                logger.info("Generated PDF report via Playwright Chromium: %s", output_path)
                return output_path
            finally:
                await browser.close()

    def _build_header_template(self, header_text: str | None) -> str:
        title = self._escape_html(header_text or "VulNexus Security Report")
        return (
            "<div style='font-size:9px;width:100%;padding:0 14px;color:#475569;display:flex;justify-content:space-between;'>"
            f"<span>{title}</span>"
            "<span class='date'></span>"
            "</div>"
        )

    def _build_footer_template(self, footer_text: str | None) -> str:
        label = self._escape_html(footer_text or "Generated by VulNexus")
        return (
            "<div style='font-size:9px;width:100%;padding:0 14px;color:#64748b;display:flex;justify-content:space-between;'>"
            f"<span>{label}</span>"
            "<span>Page <span class='pageNumber'></span> of <span class='totalPages'></span></span>"
            "</div>"
        )

    @staticmethod
    def _escape_html(value: str) -> str:
        return (
            value.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&#39;")
        )


_renderer: ReportRenderer = PlaywrightChromiumRenderer()


def get_report_renderer() -> ReportRenderer:
    return _renderer


def set_report_renderer(renderer: ReportRenderer) -> None:
    global _renderer
    _renderer = renderer
